import { MobParts } from "./mob-parts";

export const MOBPARTS: MobParts[] = [
  {
    id: 1001,
    name: "Samsung Galaxy S20",
    company: "Samsung",
    img: "mobiles/galaxy-s20-ultra.jpg",
    prodColor: "aqua",
    stock: 0,
    isOnline: false,
    country: "India",
    price: 97999,
    quantity: 0,
  },
  {
    id: 1002,
    name: "Motorola Edge",
    company: "Motorola",
    img: "mobiles/motorola-edge-plus.jpg",
    prodColor: "gold",
    stock: 5,
    isOnline: true,
    country: "Australia",
    price: 74999,
    quantity: 0,
  },
  {
    id: 1003,
    name: "Motorola One Vision",
    company: "Motorola",
    img: "mobiles/motorola-one-vision-plus.jpg",
    prodColor: "green",
    stock: 8,
    isOnline: true,
    country: "",
    price: 22999,
    quantity: 0,
  },
  {
    id: 1004,
    name: "Samsung Galaxy M30",
    company: "Samsung",
    img: "mobiles/galaxy-m30.jpg",
    prodColor: "green",
    stock: 8,
    isOnline: true,
    country: "",
    price: 17499,
    quantity: 0,
  },
  {
    id: 1005,
    name: "Apple iPhone 11 Pro",
    company: "Apple",
    img: "mobiles/apple-iphone-11-pro.jpg",
    prodColor: "green",
    stock: 8,
    isOnline: true,
    country: "",
    price: 106600,
    quantity: 0,
  },
  {
    id: 1006,
    name: "Nokia 7.2",
    company: "Nokia",
    img: "mobiles/nokia-7-2.jpg",
    prodColor: "green",
    stock: 8,
    isOnline: true,
    country: "",
    price: 18099,
    quantity: 0,
  },
];
